[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "relocation-model=static",
  "-C", "link-arg=-T/usr/lib/x86_64-linux-gnu/ldscripts/elf_x86_64.x",  
  "-C", "link-arg=-Tdefmt.x"
]

[build]
target = "x86_64-unknown-linux-gnu"

[env]
DEFMT_LOG = "trace"